version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    build: kafka-docker
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: producer
    environment:
      KAFKA_BROKER_LIST: kafka:9093
      TOPIC_NAMES: sensor0
  consumer-python:
    build: python/src
    environment:
      KAFKA_BROKER_LIST: kafka:9093
      TOPIC_NAME: sensor0
  consumer:
    build: java-consumer-docker
    #image: nichemley/minimal-kafka
    environment:
      CONSUMER_GROUP_ID: consumer-group-0
      BOOTSTRAP_SERVERS: localhost:9092
      TOPIC_NAMES: sensor0 

